### Login
POST {{serverAddress}}/hero/auth/login
Accept: application/json

{
  "email": "{{email}}",
  "password":"{{password}}"
}

> {%
    client.global.set("auth_token", response.body.result.token)
%}

### Get Magic Link
POST {{serverAddress}}/hero/auth/login/get-magic-link
Accept: application/json

{
  "email": "{{email}}"
}

### Validate Magic Link
POST {{serverAddress}}/hero/auth/login/validate-magic-link
Accept: application/json

{
  "token": "{{magic-link-token}}"
}
> {%
    client.global.set("auth_token", response.body.result.token)
%}

### Singup
POST {{serverAddress}}/hero/auth/signup
Accept: application/json

{
  "email": "some-working-email@example.com",
  "password":"some-new-password",
  "first_name": "Your name"
}

> {%
    client.global.set("auth_token", response.body.result.token)
%}


### Profile
GET {{serverAddress}}/hero/profile
Accept: application/json
Authorization: Bearer {{auth_token}}

### Update Profile
POST {{serverAddress}}/hero/profile
Accept: application/json
Authorization: Bearer {{auth_token}}

{
    "first_name": "Elliot",
    "last_name": "Alderson",
    "instagram": null,
    "telegram": null,
    "phone": null,
    "about": "do coding and stuff"
}

### Update Password
POST {{serverAddress}}/hero/profile/password
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "password":"12345678"
}

### Courses
GET {{serverAddress}}/hero/courses
Accept: application/json
Authorization: Bearer {{auth_token}}

### Course
GET {{serverAddress}}/hero/courses/{{courseSlug}}/lessons
Accept: application/json
Authorization: Bearer {{auth_token}}

### Course Feed
GET {{serverAddress}}/hero/courses/{{courseSlug}}/feed?skip=0&limit=2
Accept: application/json
Authorization: Bearer {{auth_token}}

### Course Personal Feed For User
GET {{serverAddress}}/hero/courses/{{courseSlug}}/feed/personal?skip=0&limit=6
Accept: application/json
Authorization: Bearer {{auth_token}}

### Lesson
GET {{serverAddress}}/hero/courses/{{courseSlug}}/lessons/{{lessonSlug}}
Accept: application/json
Authorization: Bearer {{auth_token}}

### Complete Lesson
POST {{serverAddress}}/hero/courses/{{courseSlug}}/lessons/{{lessonSlug}}
Accept: application/json
Authorization: Bearer {{auth_token}}

{}

### Lesson Solved Quizzes
GET {{serverAddress}}/hero/courses/{{courseSlug}}/lessons/{{lessonSlug}}/quizzes/{{quizSlug}}/solved?skip=0&limit=2
Accept: application/json
Authorization: Bearer {{auth_token}}

### Lesson Solve Quiz
POST {{serverAddress}}/hero/courses/{{courseSlug}}/lessons/{{lessonSlug}}/quizzes/{{quizSlug}}/solved
Accept: application/json
Authorization: Bearer {{auth_token}}

### Delete Lesson Solved Quiz
DELETE {{serverAddress}}/hero/courses/{{courseSlug}}/lessons/{{lessonSlug}}/quizzes/{{quizSlug}}/solved
Accept: application/json
Authorization: Bearer {{auth_token}}

### Offer
GET {{serverAddress}}/hero/offers/{{offerSlug}}
Accept: application/json